{
 "title": "Polkadot metrics",
 "description": "Grafana dashboard compatible with all the polkadot and substrate based blockchains.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "State Cache Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "target": "used_state_cache_size", "type": "timeseries" }
   ]
  },
  {
   "title": "Block Heights",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "finalized_height", "type": "timeseries" },
    { "target": "height", "type": "timeseries" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "bandwidth_upload", "type": "timeseries" },
    { "target": "bandwidth_download", "type": "timeseries" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "peers", "type": "timeseries" }
   ]
  },
  {
   "title": "DB Cache Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "target": "used_db_cache_size", "type": "timeseries" }
   ]
  },
  {
   "title": "Disc IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "disk_read_per_sec", "type": "timeseries" },
    { "target": "disk_write_per_sec", "type": "timeseries" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "memory", "type": "timeseries" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "cpu", "type": "timeseries" }
   ]
  }
 ]
}